SHELL := /bin/bash

.PHONY: docs-build docs-serve docs-up docs-down docs-clean

docs-build:
	bash ./build.sh

docs-serve:
	bash ./serve.sh

docs-up:
	bash ./serve.sh --background

docs-down:
	bash ./clean.sh

docs-clean:
	bash ./clean.sh
